<?php
    $url = $this->baseUrl(); 
?>
<div class="container">
	<div class="page-header">
        <h1>Category Entries:</h1>
    </div>
    <div class="row">
        <div class="col-md-6">
            <table class="table">
                <thead>
                    <tr><th>Id</th><th>Name</th><th>Description</th><th>Created Date</th><th>Actions</th></tr>
                </thead>
                <tbody>
                    <?php foreach ($this->entries as $entry): ?>
                        <tr>
                            <td><?php echo $this->escape($entry->id) ?></td>
                            <td><?php echo $this->escape($entry->name) ?></td>
                            <td><?php echo $this->escape($entry->desc) ?></td>
                            <td><?php echo $this->escape($entry->createddt) ?></td>
                            <td>
                                <a href="category/view/id/<?=$this->escape($entry->id) ?>">View</a>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
	</div>
</div>