<!DOCTYPE html>
<!-- http://getbootstrap.com/examples/theme/ -->
<html lang="en">
	<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <?php   // disabling client-side cache
    echo $this->headMeta()->appendHttpEquiv('expires', 'Wed, 26 Feb 1997 08:21:57 GMT')
        ->appendHttpEquiv('pragma', 'no-cache')
        ->appendHttpEquiv('Cache-Control', 'no-cache');
    ?>
    <!-- Bootstrap core CSS -->
    <?php
        // setting links in a view script:
        echo $this->headLink()->appendStylesheet('/bootstrap/css/bootstrap.min.css');
        echo $this->headLink()->appendStylesheet('/bootstrap/css/bootstrap-theme.min.css');
        echo $this->headLink()->appendStylesheet('/bootstrap/css/theme.css');

    ?>
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- <script src="/bootstrap/js/ie-emulation-modes-warning.js"></script> -->
    <?php echo $this->headScript()->appendFile('/bootstrap/js/ie-emulation-modes-warning.js', 'text/javascript'); ?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
	<body>
		<!-- Fixed navbar -->
		    <nav class="navbar navbar-inverse navbar-fixed-top">
		      <div class="container">
		        <div class="navbar-header">
		          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		            <span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		          </button>
		          <a class="navbar-brand" href="/">Bootstrap theme</a>
		        </div>
		        <div id="navbar" class="navbar-collapse collapse">
		          <ul class="nav navbar-nav">
		            <li class="active"><a href="/">Home</a></li>
		            <li><a href="/category">Category</a></li>
		            <li class="dropdown">
		              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
		              <ul class="dropdown-menu" role="menu">
		                <li><a href="/category">Category</a></li>
		                <li><a href="#">Another action</a></li>
		                <li><a href="#">Something else here</a></li>
		                <li class="divider"></li>
		                <li class="dropdown-header">Nav header</li>
		                <li><a href="#">Separated link</a></li>
		                <li><a href="#">One more separated link</a></li>
		              </ul>
		            </li>
		          </ul>
		        </div><!--/.nav-collapse -->
		      </div>
		    </nav>
		

		<div class="container">
			<?php echo $this->layout()->content ?>
		</div>
		
		<!-- Fixed navbar -->
		    <nav class="navbar navbar-inverse navbar-fixed-bottom">
		      <div class="container">
		        <div class="navbar-footer">
		          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
		            <span class="sr-only">Toggle navigation</span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
		          </button>
		          <a class="navbar-brand" href="#">Bootstrap theme</a>
		          <ul class="nav navbar-nav">
		            <li class="active"><a href="#">Home</a></li>
		            <li><a href="#about">About</a></li>
		            <li><a href="#contact">Contact</a></li> 
		          </ul>
		        </div> 
		      </div> 
		    </nav>
      
		<!-- jQuery -->
		<!-- <script src="/js/jquery.min.js"></script> -->
		<!-- Bootstrap Core JavaScript -->
		<!-- <script src="/bootstrap/js/bootstrap.min.js"></script> -->
        <?php echo $this->headScript()->appendFile('/js/jquery.min.js', 'text/javascript'); ?>
        <?php echo $this->headScript()->appendFile('/bootstrap/js/bootstrap.min.js', 'text/javascript'); ?>

	</body>

</html>